spring.application.name=com.sproutsync

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

auth.jwt.expirationDays=30
auth.jwt.secret=${JWT_SECRET}
auth.jwt.issuer=sprout-backend